version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "ymtdzzz"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/tuiexporter"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "ymtdzzz"
    groups:
      dependencies:
        patterns:
          - "*"
